### ISSUE TITLE
Syntax highlighting not working in helix editor in mac

### ISSUE THREAD

**Issue by mgpinf** [uben0/tree-sitter-typst#12]
I followed the steps mentioned in `README.md`, still doesn't work. Not sure why.

OS: `MacOS (M2)`

### Typst code:
<img width="1400" alt="image" src="https://github.com/uben0/tree-sitter-typst/assets/56510798/c07a136f-f01c-49bc-b522-f375a8475d3f">

I set `$HELIX_RUNTIME` to `$HOME/.config/helix/runtime`

### languages.toml
```toml
[[language]]
name = "typst"
scope = "source.typst"
file-types = ["typst", "typ"]
roots = []
indent = { tab-width = 2, unit = "  " }
comment-token = "//"
injection-regex = "typ(st)?"
# language-servers = [ "typst-lsp" ]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'

[[grammar]]
name = "typst"
source.git = "https://github.com/uben0/tree-sitter-typst"
source.rev = "60843a0604120c3014507f9635300264ba0e547e"
```

### Runtime directory structure:
<img width="472" alt="image" src="https://github.com/uben0/tree-sitter-typst/assets/56510798/5365ea8e-bf8e-4fb6-b347-deb3f11cd712">
